Adding an additional fasted-MTU tunnel size of 1312 Byte on Port 10004
freifunk-ffm/supernode_puppet pull request #24
Opened 2017-02-18 12:26 UTC by oszilloskop

Als Fallback für fastd-MTU wird eine Größe von 1312 Byte eingestellt.
Diese fastd-MTU stellt die kleinstmögliche Größe dar, um mindestens 1280 Byte Payload durch den Fastd-Tunnel transportiert zu können.

2017-02-18 14:29 UTC, skorpy2009 commented
dieser macvendor exestiert schon.

2017-02-18 14:30 UTC, skorpy2009 requested changes
macvendor

2017-02-18 15:11 UTC, oszilloskop commented
@skorpy2009 
Vorschlag?

2017-02-18 15:24 UTC, oszilloskop commented
-v
'macvendor' der eingefügten Section 'mesh-vpn-1312' ist wohl identisch wie in Section 'mesh-vpn-1374' (diese Section hat als Vorlage für die Initialänderung hergehalten).

'macvendor' in 'mesh-vpn-1312' wurde von '02:ff:3f' auf '02:ff:4f' geändert (analog zu der Benamsung der bisherigen alten Sections).

Done.

2017-02-18 21:47 UTC, christf commented
muss es denn wirklich ein vierter fastd-Port sein oder können wir einen bestehenden ersetzen?

2017-02-18 21:49 UTC, skorpy2009 commented
>muss es denn wirklich ein vierter fastd-Port sein oder können wir einen bestehenden ersetzen?
Ja muss ein eigener sein damit Router die noch auf alter Firmware sind noch weiter funktionieren. Was spricht gegen weitere Ports?

2017-02-18 22:51 UTC, christf commented
Das wir teilweise gw hinter nat haben und das wieder gefummel ist. 
Die Alten firmwares verbinden sich zu 2 ports. Was ist mit dem dritten? 

Am 18. Februar 2017 22:49:34 MEZ schrieb skorpy2009 <notifications@github.com>:
>>muss es denn wirklich ein vierter fastd-Port sein oder können wir
>einen bestehenden ersetzen?
>Ja muss ein eigener sein damit Router die noch auf alter Firmware sind
>noch weiter funktionieren. Was spricht gegen weitere Ports?

Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

2017-02-19 11:45 UTC, oszilloskop commented
Die bereits zwei verwendeten fastd-Ports werden von der aktuellen Stable benutzt.

Wenn wir zwei neue fastd-MTUs einbringen wollen, müssen wir leider im ersten Schritt auch zwei freie 'neue' Ports verwenden.
Wenn eine Umstellung der Firmware dann mal rum ist, und keine 'alte Stable' mehr im Feld ist, können wir wieder reduzieren. 

Oder wir unterstützen mit der geplanten neuen Firmware nur noch eine fastd-MTU. Dann bräuchten wir keinen vierten Port auf den Supernodes.

2017-02-19 21:22 UTC, skorpy2009 approved these changes
Sollte laufen...

2017-02-19 21:23 UTC, merged