Christf block smtp
freifunk-ffm/supernode_puppet pull request #25
Opened 2017-05-03 19:39 UTC by christf

2017-05-03 19:42 UTC, skorpy2009 requested changes

2017-05-03 19:42 UTC, skorpy2009 commented on modules/fastd/templates/on_verify_batman.erb
> +connection_average_estimate=$(( 2 * net_peer_amount / gwamount ))
NEIN! Aktuell sind da schon zu viele VPNs zu einem GW.

2017-05-03 19:46 UTC, christf commented on modules/fastd/templates/on_verify_batman.erb
> +connection_average_estimate=$(( 2 * net_peer_amount / gwamount ))
ist eh schon auf dem master. dsa führt die stände nur wieder zusammen....

2017-05-03 19:49 UTC, skorpy2009 commented on modules/shorewall/manifests/four/rule.pp
> +    action  => 'SMTP(DROP)',
@t-8ch passt das so?

2017-05-03 19:49 UTC, skorpy2009 commented on modules/fastd/templates/on_verify_batman.erb
> +connection_average_estimate=$(( 2 * net_peer_amount / gwamount ))
Das ist aber kein Argument.

2017-05-04 08:00 UTC, t-8ch commented on modules/shorewall/manifests/four/rule.pp
> +    action  => 'SMTP(DROP)',
Das blockiert auch das SMTP, das vom Server selbst initiiert ist.
Außerdem ist das in der falschen Datei. Das sollte iwo nach supornode.pp

2017-05-08 20:18 UTC, christf commented on modules/shorewall/manifests/four/rule.pp
> +    action  => 'SMTP(DROP)',
@t-8ch in welche datei soll das genau? ich finde keine supernode.pp im shorewall kontext.

2017-05-08 20:24 UTC, christf commented on modules/shorewall/manifests/four/rule.pp
> +    action  => 'SMTP(DROP)',
btw: port 25 ausgehend auch vom server aus zu blocken war durchaus absicht. der muss da nicht kommunizieren.

2017-05-09 20:57 UTC, christf commented
@t-8ch @skorpy2009 was meint ihr? besser?

2017-05-10 18:25 UTC, skorpy2009 requested changes

2017-05-10 18:25 UTC, skorpy2009 commented on modules/fastd/templates/on_verify_batman.erb
> +connection_average_estimate=$(( 2 * net_peer_amount / gwamount ))
Beim nächsten Treffen reden wir noch mal über die Zahl, aber das kommt hier jetzt nur rein weil es schon drauf ist!

2017-05-10 18:25 UTC, skorpy2009 commented on modules/ffmff/manifests/supernode.pp
> +      destination => 'net',
warum nicht open VPN blocken; alle unsere Dienstleister blocken es: Mullvad, ipredator und AirVPN blocken Port 25;

warum CPU / OpenVPN dafür verschwenden?

2017-05-10 18:38 UTC, skorpy2009 requested changes

2017-05-10 18:38 UTC, skorpy2009 commented on modules/ffmff/manifests/supernode.pp
> +      destination => 'net',
nope; not this way.
`destination => ['net', 'ovpn'],`
maybe but not twice the same rule

2017-05-16 13:13 UTC, skorpy2009 approved these changes

2017-05-16 13:13 UTC, merged